### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [trevorbalint/covid-19#2]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/R8ANEK
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by trevorbalint** [comment]
> Hello,
> Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/R8ANEK
> Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

Hi, I'd strongly suggest against using my dataset for this purpose. These data are taken directly from the JHU COVID data without verification or modification, so it's redundant at best and reinforcing one particular data source at worst.

**Comment by k-goncharova** [comment]
Hi Trevor, thanks a lot for your comments. We deaccessioned the dataset from CoronaWhy Dataverse. Our goal is to create a trustworthy dataframe for scientists, not just add unnecessary noise.
